---
AWSTemplateFormatVersion: 2010-09-09
Description: Provisions HIPAA Ready Environment in AWS (qs-1rabh51gu)
Metadata:
  Identifier:
    Value: main
  Input:
    Description: Input of all required parameters in nested stacks
  Output:
    Description: N/A
  cfn-lint: { config: { ignore_checks: [ W3011 ] } }
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: AWS config configuration
      Parameters:
      - AWSConfigARN
    - Label:
        default: AWS quick-start configuration
      Parameters:
      - QSS3BucketName
      - QSS3KeyPrefix
    ParameterLabels:
      AWSConfigARN:
        default: AWS config service linked role ARN
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
Parameters:
  AWSConfigARN:
    Type: String
    Description: AWS config service linked role ARN.
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-.]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, periods (.), and hyphens (-). It cannot start or
      end with a hyphen (-).
    Default: aws-quickstart
    Description: S3 bucket name for the Quick Start assets. Quick Start bucket name
      can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slash (/).
    Default: quickstart-compliance-hipaa/
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
Resources:
  AWSConfigLoggingBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Name
          Value: AWS Config Logging Bucket
        - Key: Purpose
          Value: Security
  AWSConfigBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    DeletionPolicy: Retain
    Properties:
      Bucket: !Ref AWSConfigLoggingBucket
      PolicyDocument:
        Version: 2012-10-17
        Id: AWSConfigAccessToBucket
        Statement:
          - Sid: AWSConfigBucketPermissionsCheck
            Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action: 's3:GetBucketAcl'
            Resource: !GetAtt 
              - AWSConfigLoggingBucket
              - Arn
          - Sid: AWSConfigBucketDelivery
            Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action: 's3:PutObject'
            Resource: !Join 
              - ''
              - - !GetAtt 
                  - AWSConfigLoggingBucket
                  - Arn
                - /*
            Condition:
              StringEquals:
                's3:x-amz-acl': bucket-owner-full-control
  # Used to create a short dynamic name
  PsuedoRandom:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: DoNotUse
  AWSConfigDeliveryChannel:
    Type: 'AWS::Config::DeliveryChannel'
    Properties:
      S3BucketName: !Ref AWSConfigLoggingBucket
      Name: !Sub "default-${PsuedoRandom.GroupId}"
  AWSConfigConfigurationRecorder:
    Type: 'AWS::Config::ConfigurationRecorder'
    Properties:
      RoleARN: !Ref AWSConfigARN
      Name: !Sub "default-${PsuedoRandom.GroupId}"
  AWSConfigHIPAAConformancePack:
    Type: 'AWS::Config::ConformancePack'
    Properties:
      ConformancePackName: aws-config-hipaa-conformance-pack
      TemplateS3Uri: !Join 
        - ''
        - - 's3://'
          - !Ref QSS3BucketName
          - '/'
          - !Ref QSS3KeyPrefix
          - 'templates/hipaa/Operational-Best-Practices-for-HIPAA-Security.yaml'
Outputs:
  Help:
    Description: For assistance or questions regarding this quickstart please email compliance-accelerator@amazon.com
    Value: ''
...